new FPGA BitFile - fixes MPU problems

diff --git a/init b/init
--- a/init
+++ b/init
@@ -43,10 +43,16 @@ startdaemon(){
 	start-stop-daemon --start --oknodo --pidfile ${PIDFILE} --startas $DAEMON -- -p ${PIDFILE} -u m1m3:m1m3
 	echo "done"
 }
+
 stopdaemon(){
 	echo -n "Stopping TS M1M3 thermal:"
-	start-stop-daemon --stop --oknodo --remove-pidfile --retry 5 -p ${PIDFILE}
-	echo "done"
+	start-stop-daemon --stop --remove-pidfile --retry 5 -p ${PIDFILE}
+        if [ $? == 0 ]; then
+	    echo "done"
+        else
+            echo "failed"
+            exit $?
+        fi
 }
 
 case "$1" in
